---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./kyverno.yaml
  - ./piraeus.yaml
  - ./rook-ceph.yaml
  - ./apache-tika.yaml
  - ./node-feature-discovery.yaml
  - ./emxq.yaml
  - ./cloudnative-pg.yaml
  - ./democratic-csi.yaml
  - ./csi-driver-nfs.yaml
