---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  METALLB_LB_RANGE: "192.168.10.200-192.168.10.230"
  KUBE_VIP_ADDR: "192.168.10.80"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  LOCAL_LAN_TRUENAS: 192.168.10.10
  LOCAL_LAN_PFSENSE: 192.168.10.1
  INTERNAL_DNS_IP: 192.168.10.7
  LB_PAPERLESS_IP: 192.168.10.222
  LB_TVHEADEND_IP: 192.168.10.223
  LB_JELLYFIN_IP: 192.168.10.224
  LB_HOMEASSISTANT_IP: 192.168.10.225
  LB_EMQX_IP: 192.168.10.226
  LB_ADGUARD_IP: 192.168.10.101
  POSTGRES_HOST: "postgres-rw.database.svc.cluster.local."
  POSTGRES_PORT: "5432"
  NETWORK_BGP_SVC_RANGE: 192.168.10.0/24
  METALLB_INGRESS_ADDR: 192.168.10.200
  METALLB_K8S_GATEWAY_ADDR: 192.168.10.220
