---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.10.80"
  METALLB_LB_RANGE: "192.168.10.150-192.168.10.230"
  METALLB_K8S_GATEWAY_ADDR: "192.168.10.220"
  METALLB_INGRESS_ADDR: "192.168.10.200"
  CLUSTER_NAME: "cluster01"
  CLUSTER_ID: "1"
  DOMAIN_INTERNAL: k3s.home.lan
  LOCAL_LAN_TRUENAS: 192.168.10.10
  LOCAL_LAN_PFSENSE: 192.168.10.1
  INTERNAL_DNS_IP: 192.168.10.7
  METALLB_LB_CLIENT_RANGE: 192.168.30.150-192.168.30.230
  LB_PAPERLESS_IP: 192.168.10.222
  LB_TVHEADEND_IP: 192.168.10.223
  LB_JELLYFIN_IP: 192.168.10.224
  LB_HOMEASSISTANT_IP: 192.168.10.225
  LB_EMQX_IP: 192.168.10.226
  LB_ADGUARD_IP: 192.168.10.101
  POSTGRES_HOST: "postgres-rw.database.svc.cluster.local."
  POSTGRES_PORT: "5432"
